version: '3'
services:
  postgres:
    image: 'postgres:11.15'
    restart: always
    ports:
      - '5430:5432'
    environment:
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
      POSTGRES_DB: '${DB_NAME}'